name: pricelocq_assessment
description: PriceLOCQ Assessment Test

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations: 
    sdk: flutter 
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  bloc_test: ^9.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  intl: any
  geolocator: ^6.1.14
  google_maps_flutter: ^2.0.10
  mockito: ^5.3.2
  dio: ^5.0.1
  flutter_secure_storage: ^4.2.1
  bloc_concurrency: ^0.2.1

dependency_overrides:
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true